from pathlib import Path

MODEL_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = MODEL_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"

# MLB
MLB_RAW_DIR = RAW_DIR / "mlb"
MLB_LAHMAN_DIR = MLB_RAW_DIR / "lahman_1871_2024u"
MLB_PROCESSED_DIR = PROCESSED_DIR / "mlb"

# NFL
NFL_PROCESSED_DIR = PROCESSED_DIR / "nfl"

# NHL
NHL_PROCESSED_DIR = PROCESSED_DIR / "nhl"

# UFC
UFC_PROCESSED_DIR = PROCESSED_DIR / "ufc"

MODEL_DIR = MODEL_ROOT
ARTIFACTS_DIR = MODEL_ROOT / "artifacts"
NFL_ARTIFACTS_DIR = ARTIFACTS_DIR / "nfl"